### ISSUE TITLE
Become an administrator button not appearing

### ISSUE THREAD

**Issue by rogervila** [tlkio/feedback#7]
Hello,

Even though I'm connected with 3 real accounts from Twitter and Facebook, I can't become an admin.

I've been [following this article](http://blog.tlk.io/post/105771925713/how-to-become-a-moderator), but the button does not appear.

Am I missing something?

Thak you very much

**Comment by antstorm** [comment]
@rogervila you might need to wait until all the messages in the current chat disappear (should happen after 10 minutes of inactivity). This is done in order to not allow others to "take over" an active chat room

**Comment by rogervila** [comment]
Thank you @antstorm :)
