### ISSUE TITLE
forum 48 hours delete

### ISSUE THREAD

**Issue by RichGriese** [tlkio/feedback#8]
Hey Antman,

Remember me? Your auto deleting my channel posts after 48 hours. Could you add another channel to that list. https://tlk.io/forum

I hope it's not a bother you while your dealing with your connection issues, but since your probably right there in the code, I'm hoping it's not any kind of pain.

Cheers!

**Comment by RichGriese** [comment]
Was justing looking and the test post I've got in https://tlk.io/ChurchOfStarbucks is not just over 2 days old... I'm gonna assume that means the 48 hour delete is not yet set up. When you get a chance... I'll just keep checking to see when that test item goes away, before I link the forum/chat into the site, but I thought I'd just give you a reminder. Cheers!

**Comment by RichGriese** [comment]
@antstorm Sorry to be even more of a pain in your ass. I decided to change the forum to have you add to the 48 hour delete from #ChurchOfStarbucks to... https://tlk.io/forum. Lot's of reasons, but it will be a lot less confusing on the http://ChurchOfStarbucks.net world to talk abut "the forum" this way. Cheers!

**Comment by antstorm** [comment]
@RichGriese so just to be clear — you want to set expiration of messages on the tlk.io/forum to 48h, right?

**Comment by RichGriese** [comment]
@antstorm... Yes. Sorry to be unclear. Cheers!

**Comment by antstorm** [comment]
@RichGriese no worries, done!

**Comment by RichGriese** [comment]
@antstorm, Awesome... thanks.

**Comment by RichGriese** [comment]
@antstorm, sorry... I know your gonna hate me. But... I swapped ownership of two channels #forum and #webulite and now I notice that 48 hours auto delete is not happening on them. Could you add 48 hour message auto-delete back to them? Sorry to be such a pain in your ass. Cheers!

**Comment by antstorm** [comment]
@RichGriese no worries, I've updated both of your channels
